version: '3'
services:
  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'
  redis:
    image: redis
    restart: always
    volumes:
      - redisdata:/data
    ports:
      - '6379:6379'
volumes:
  pgdata:
  mongodata:
  redisdata:
